name = "redmont-economic-news"
main = "src/index.js"
compatibility_date = "2026-06-01"

# After `npx wrangler d1 create ren-db`, paste the printed database_id below.
[[d1_databases]]
binding = "DB"
database_name = "ren-db"
database_id = "988c6817-a279-40e7-a4ea-225c66e50154"